# Generated by Django 5.2.3 on 2025-06-15 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Telefon'), ('monitor', 'Monitor'), ('printer', 'Drukarka'), ('server', 'Serwer'), ('router', 'Router'), ('other', 'Inne')], max_length=32)),
                ('inventory_number', models.CharField(max_length=64, unique=True)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Dostępny'), ('in_use', 'Używany'), ('in_repair', 'W naprawie'), ('retired', 'Wycofany')], default='available', max_length=16)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('assigned', 'Przypisanie'), ('unassigned', 'Zwolnienie'), ('repair', 'Naprawa'), ('retired', 'Wycofanie'), ('other', 'Inne')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
