# Generated by Django 5.2.3 on 2025-06-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='purchase_date',
        ),
    ]
